---
name: "Release"

'on':
  workflow_dispatch:
  push:
    branches: ["release"]

jobs:
  release:
    name: 'apps:release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'release'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
